name: CI demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    if: github.event.head_commit == null || !contains(github.event.head_commit.message, 'taking-notes')
    runs-on: [self-hosted, local]
    container: node:26-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: app
        run: |
          npm install

      - name: Run unit tests
        working-directory: app
        run: |
          echo "Running unit tests for micro service ${{ vars.MICRO_SERVICE_NAME }} ..."
          npm test
          
      - name: Upload JUnit test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: app/junit.xml
